### ISSUE TITLE
enable_seqscan = off ?

### ISSUE THREAD

**Issue by e7e6** [doctolib/pg_check_index#2]
Bonjour,
je n'ai pas encore pu tester correctement pg_check_indexes, mais en regardant le code, je vois 
```
SET enable_indexscan = on;
SET enable_indexonlyscan = on;
```
Pour ces vérifications, ne faudrait-il pas mettre également 
```
SET enable_seqscan = off;
```
Afin d'être sûr que les index soient utilisés?

**Comment by flaviogurgel** [comment]
Bonjour @e7e6  

Effectivement, ce que t'as dit c'est bien dans le code, je t'invite à regarder mieux :smile: 

Merci pour l'intérêt sur pg_check_indexes,
Flavio
